stages:
  - build
  - test

# Deploy branches only
deploy-job:
  script:
    - whoami
    - hostname
    - pwd
    - mvn -v
    - mvn --batch-mode --errors -U clean deploy
  stage: build
  only:
    - branches
  tags:
    - Java8-Nexus3

sonarqube-job:
  stage: build
  only:
    - master
  script:
    - mvn --batch-mode --errors -U clean compile sonar:sonar -Dsonar.host.url=http://sonarqube.rcsb.org -Dsonar.login=811b2df8adf3152b8191a25fe816b7524f0a452b
  tags:
    - sonarqube
